In [2]:
import numpy as np

1. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [4]:
# answer

array_1=np.random.random([5,5])
max_1=np.max(array_1)
min_1=np.min(array_1)
print(f"maxamum={max_1} \nminimum={min_1}")

maxamum=0.9896495363388508 
minimum=0.01164589372361946


2. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [5]:
# answer
array_1=np.random.random([10,4])
array_2=array_1[0:5,:]
print(array_2)

[[0.95602434 0.2398077  0.56777431 0.15858273]
 [0.48234271 0.07970231 0.38669049 0.51925043]
 [0.73556038 0.25804533 0.51853037 0.23014954]
 [0.40308009 0.39996677 0.19828707 0.41642907]
 [0.38330301 0.10205393 0.24216957 0.88543059]]


3. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [6]:
# answer
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.95604807 0.67277074 0.21854942 0.96537925 0.43222995 0.34536534
 0.03632673 0.9675756  0.20410114 0.80879535 0.31839591 0.27443843
 0.47199339 0.70240194 0.86450274]
Maximum value replaced by -1:
[ 0.95604807  0.67277074  0.21854942  0.96537925  0.43222995  0.34536534
  0.03632673 -1.          0.20410114  0.80879535  0.31839591  0.27443843
  0.47199339  0.70240194  0.86450274]


4. normalize an array so the values range exactly between 0 and 1?

In [7]:
array = np.random.randint(0, 1000, (1, 100))
# answer
array_1=np.linalg.norm(array)
normlize=array/array_1
print(normlize)

[[0.1628514  0.07974335 0.01295409 0.02658112 0.13845734 0.01413173
  0.02994582 0.09656684 0.11860562 0.158982   0.14737379 0.07907041
  0.03633874 0.10733388 0.04861989 0.12348443 0.06174221 0.09909037
  0.10127742 0.01598232 0.09353861 0.1377844  0.08310805 0.11254916
  0.12129738 0.00857998 0.05080695 0.16100082 0.05804105 0.14299968
  0.11187622 0.05568576 0.09084686 0.08731392 0.13929851 0.06308809
  0.06207868 0.06005987 0.01312232 0.03667521 0.13660675 0.00538352
  0.14249498 0.15847729 0.11305386 0.07015396 0.01564585 0.00757057
  0.01800114 0.11238093 0.05080695 0.11053034 0.13458793 0.16083258
  0.07250925 0.03162816 0.09084686 0.16789845 0.1098574  0.025067
  0.07839747 0.05383517 0.1411491  0.12314796 0.01244938 0.08933274
  0.07133161 0.01951525 0.12062444 0.12600795 0.09976331 0.12937265
  0.09774449 0.05518105 0.13677499 0.14417732 0.0597234  0.13627028
  0.00420587 0.04744225 0.00555175 0.08310805 0.0708269  0.12533501
  0.01833761 0.14636438 0.13223265 0.11810091 0.04

5. convert an nd array of arrays into a flat 1d array

In [8]:
# answer
a = np.array([[1,2,3], [4,5,6]])
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

6. from 2010 to 2018 group weekdays and weekends in two lists

notes: you are allowed to just use datetime or numpy datetime

In [17]:
# answer

data_1= np.arange('2010-01', '2018-01', dtype='datetime64[D]')

normal_day=[]
b=0
normal_day.append(data_1[0])
for i in data_1:
    a= data_1[3+b:8+b]
    normal_day.append(a)
    b+=7
    
# print("Normal day:")
# for i in range(418):
#     print(normal_day[i])

print(normal_day[1])
    
print("-----------------------------")

weekends=[]
b=0
for i in data_1:
    a= data_1[1+b:3+b]
    weekends.append(a)
    b+=7

# print("weekends:")
# for i in range(418):
#     print(weekends[i])
        
print(weekends[1])



['2010-01-04' '2010-01-05' '2010-01-06' '2010-01-07' '2010-01-08']
-----------------------------
['2010-01-09' '2010-01-10']


7. Considering a four dimensions array, how to get sum over the last two axis at once?


In [10]:
import numpy as np
array = np.random.random((4, 5, 8, 2))
a=(array[0:3,0:3,6:9,0:3]).sum(axis=(0,1))
print(a)

[[5.14918722 3.80852435]
 [3.49322512 3.7425928 ]]


8. Consider 2 points p0, p1 describing a line (2d) and a point p, how to compute distance from p to this line?

In [12]:
def distance(p0, p1, p):
    # answer
    d=np.cross(p1-p0,p-p0)/np.linalg.norm(p1-p0)
    return d

p0 = np.random.uniform(-10, 10, (1, 2))
p1 = np.random.uniform(-10, 10, (1, 2))
p  = np.random.uniform(-10, 10, (1, 2))

print(distance(p0, p1, p))

[13.38536563]


For more exercises check the following link:
https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

*:)*